{% set version = "3.1.1.3" %}

package:
  name: podman-py
  version: {{ version }}

source:
  url: https://github.com/containers/podman-py/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 507d0a56677a8ac90390792656dca2fe8487637375d64721a5efe4af34844e23

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  skip: true  # [win]

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - requests >=2.24
    - toml >=0.10.2
    - urllib3 >=1.26,<1.27

test:
  imports:
    - podman

about:
  home: https://github.com/containers/python-podman
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "Python bindings and code examples for using Varlink access to Podman Service"
  dev_url: https://github.com/containers/python-podman

extra:
  recipe-maintainers:
    - h-vetinari
    - "4383"
