travis:
  secure:
    BINSTAR_TOKEN: AxcwqeaGnAwMZmH947OPUZ1ibwTVt5uy6joP00sAZExBmEFkkdNNg58Tmj5bILDF3fwWJymWgm2Oe8D3u7q08mlG843n+x2ekwwgqNR04ds9uMDSl3NF0wJrsr7xFSGBnxUzeo6YC6AfqyCvV6inhGF45+2Wx0/7/K4RkXIcVGi8LljnlLgV6qZGDcVTZCQMD3z/UhZDOqrhU8mv1IoTt534gh8pAzBqLoIuNJUBP9pqDdYa5aliRbzvViQk64SA//kxcCD9W0obdMwciUGm4RaJi4IF3d4a2F32om9e3M/FkRwY8h6ibMZ2+IJwYX7xXwudO4cHqG3TtL2LIX12uKTz5LP3qkae8KyL11stY7TSFLbx/sbq4YsWgk56OptiqSb23IiFWZ2ZNYot3uooXNuta+B1u7c8g4YGdDiFSCzc34eVffEZVSfryrkh2S19ecYBTkyfqNUr8KPbNChykL7W5+7RIczExs8nDVeCA4rI5od5QM0ikAzm76nmpKOQHswxTHIT6G6Pt6pYdO2+lGKQngCsQmcZDU/5+JewTt8dW2R5hRb01ZbFjx9hGFswGjm2YjuGpwHeziPk+OigDv0rwKymHFiGG9erPknrc3GlAZB7syCtisgo/HnoPFH9LR3tojEDTQsT9dQb4HrAOBBSrVAfJSglKPiF1jMucBg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
